#!/bin/bash

amixer -c 0 cset name='Headphone Switch' on
amixer -c 0 cset name='Headphone Playback Volume' 3,3
amixer -c 0 cset name='Right Headphone Mixer Right DAC Switch' on
amixer -c 0 cset name='Left Headphone Mixer Left DAC Switch' on
amixer -c 0 cset name='DAC Playback Volume' 999,999
amixer -c 0 cset name='Headphone Mixer Volume' 999,999
amixer -c 0 cset name='Differential Mux' lin1-rin1
amixer -c 0 cset name='Differential Mux' lin2-rin2
amixer -c 0 cset name='DAC Soft Ramp Switch' off
# amixer -c 1 cset name='Headphone Switch' on
# amixer -c 1 cset name='Headphone Playback Volume' 3,3
# amixer -c 1 cset name='Right Headphone Mixer Right DAC Switch' on
# amixer -c 1 cset name='Left Headphone Mixer Left DAC Switch' on
# amixer -c 1 cset name='DAC Playback Volume' 999,999
# amixer -c 1 cset name='Headphone Mixer Volume' 999,999
# amixer -c 1 cset name='Differential Mux' lin1-rin1
# amixer -c 1 cset name='Differential Mux' lin2-rin2
# amixer -c 1 cset name='DAC Soft Ramp Switch' off
