format = "$username | Arch:(bold blue) $all"

[line_break]
disabled = true

[character]
success_symbol = "→(bold blue)"
error_symbol = "→(bold red)"

[username]
disabled = false
show_always = true
format = "[$user](bold cyan)"

[cmd_duration]
disabled = true

[directory]
style = "bold cyan"
