FAST_THEME_NAME=""

FAST_HIGHLIGHT_STYLES[default]=none
FAST_HIGHLIGHT_STYLES[unknown-token]=fg=white
FAST_HIGHLIGHT_STYLES[reserved-word]=fg=magenta
FAST_HIGHLIGHT_STYLES[suffix-alias]=fg=green
FAST_HIGHLIGHT_STYLES[global-alias]=fg=green
FAST_HIGHLIGHT_STYLES[precommand]=fg=cyan
FAST_HIGHLIGHT_STYLES[commandseparator]=fg=magenta
FAST_HIGHLIGHT_STYLES[autodirectory]=fg=green
FAST_HIGHLIGHT_STYLES[path]=fg=white
FAST_HIGHLIGHT_STYLES[path-separator]=none
FAST_HIGHLIGHT_STYLES[globbing]=fg=blue
FAST_HIGHLIGHT_STYLES[history-expansion]=fg=blue
FAST_HIGHLIGHT_STYLES[command-substitution]=none
FAST_HIGHLIGHT_STYLES[command-substitution-delimiter]=fg=magenta
FAST_HIGHLIGHT_STYLES[process-substitution]=none
FAST_HIGHLIGHT_STYLES[process-substitution-delimiter]=fg=magenta
FAST_HIGHLIGHT_STYLES[single-hyphen-option]=fg=green
FAST_HIGHLIGHT_STYLES[double-hyphen-option]=fg=green
FAST_HIGHLIGHT_STYLES[back-quoted-argument]=none
FAST_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]=fg=blue
FAST_HIGHLIGHT_STYLES[single-quoted-argument]=fg=yellow
FAST_HIGHLIGHT_STYLES[double-quoted-argument]=fg=yellow
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]=fg=yellow
FAST_HIGHLIGHT_STYLES[rc-quote]=fg=magenta
FAST_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=magenta
FAST_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=magenta
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]=fg=magenta
FAST_HIGHLIGHT_STYLES[assign]=none
FAST_HIGHLIGHT_STYLES[redirection]=fg=blue
FAST_HIGHLIGHT_STYLES[comment]=fg=244
FAST_HIGHLIGHT_STYLES[named-fd]=none
FAST_HIGHLIGHT_STYLES[numeric-fd]=none
FAST_HIGHLIGHT_STYLES[arg0]=fg=blue
FAST_HIGHLIGHT_STYLES[bracket-error]=fg=red
FAST_HIGHLIGHT_STYLES[bracket-level-1]=fg=blue
FAST_HIGHLIGHT_STYLES[bracket-level-2]=fg=green
FAST_HIGHLIGHT_STYLES[bracket-level-3]=fg=magenta
FAST_HIGHLIGHT_STYLES[bracket-level-4]=fg=yellow
FAST_HIGHLIGHT_STYLES[bracket-level-5]=fg=cyan
FAST_HIGHLIGHT_STYLES[cursor-matchingbracket]=standout
FAST_HIGHLIGHT_STYLES[alias]=fg=blue
FAST_HIGHLIGHT_STYLES[function]=fg=blue
FAST_HIGHLIGHT_STYLES[builtin]=fg=cyan
FAST_HIGHLIGHT_STYLES[command]=fg=blue
FAST_HIGHLIGHT_STYLES[hashed-command]=fg=blue
FAST_HIGHLIGHT_STYLES[number]=fg=cyan
FAST_HIGHLIGHT_STYLES[variable]=fg=cyan
